/*
 * App API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: v1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

import (
	"time"
)

type WctApiApplicationOrderDtoOrderExpressDto struct {
	Result struct {
		// 快递公司
		ExpressId int32 `json:"ExpressId,omitempty"`
		// 快递单号
		ExpressCode string `json:"ExpressCode,omitempty"`
		// 快递状态
		ExpressStatus string `json:"ExpressStatus,omitempty"`
		// 快递公司
		Express string `json:"Express,omitempty"`
		// 创建时间
		CreationTime time.Time `json:"CreationTime,omitempty"`
		// 创建人
		CreatorUserName string `json:"CreatorUserName,omitempty"`
		// 联系人
		Linkman string `json:"Linkman,omitempty"`
		// 联系号码
		Telephone string `json:"Telephone,omitempty"`
		// 物流公司logo
		CompanyLogoUrl string `json:"CompanyLogoUrl,omitempty"`
		// 是否是大物流公司
		IsCompany bool `json:"IsCompany,omitempty"`
	} `json:"result"`
	TargetURL           interface{} `json:"targetUrl"`
	Success             bool        `json:"success"`
	Error               interface{} `json:"error"`
	UnAuthorizedRequest bool        `json:"unAuthorizedRequest"`
	Abp                 bool        `json:"__abp"`
}
