/*
 * App API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: v1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type WctApiApplicationAuthorizationDtoRegisterModel struct {
	// 绑定的手机号码/邮箱
	BindAccount string `json:"BindAccount"`
	// 短信验证码
	SmsCode string `json:"SmsCode"`
	// 密码
	Password string `json:"Password"`
}
