/*
 * App API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: v1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type WctApiModelsTokenAuthExternalAuthenticateModel struct {
	AuthProvider string `json:"AuthProvider"`
	CodeOrIdToken string `json:"CodeOrIdToken"`
}
