/*
 * App API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: v1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type AbpApplicationServicesDtoEntityDto1SystemInt64 struct {
	Id int64 `json:"Id,omitempty"`
}
