/*
 * App API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: v1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type WctApiAboutDtoAboutDetailDto struct {
	// 客服电话
	ConsumerHotline string `json:"ConsumerHotline,omitempty"`
	// 客服时间-星期
	ServiceWeek []int32 `json:"ServiceWeek,omitempty"`
	// 客服时间-时间
	ServiceBeginTime string `json:"ServiceBeginTime,omitempty"`
	// 客服时间-时间
	ServiceEndTime string `json:"ServiceEndTime,omitempty"`
	// 关于
	AboutUs string `json:"AboutUs,omitempty"`
}
