/*
 * App API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: v1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type WctApiModelsTokenAuthAuthenticateModel struct {
	LoginType int32 `json:"LoginType"`
	UserName string `json:"UserName,omitempty"`
	Password string `json:"Password,omitempty"`
	SmsCode string `json:"SmsCode,omitempty"`
	ImageKey string `json:"ImageKey,omitempty"`
	ImageCode string `json:"ImageCode,omitempty"`
}
